// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwUvKJ11riND1jBT2ocu2D5tzSpdpE7QI',
    appId: '1:910147898524:web:03323471d564230350b159',
    messagingSenderId: '910147898524',
    projectId: 'decen--backend',
    authDomain: 'decen--backend.firebaseapp.com',
    storageBucket: 'decen--backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl0Al_SfIXqw52DOxzIGCX_p7JvBDvzr8',
    appId: '1:910147898524:android:b9773b89cea58abe50b159',
    messagingSenderId: '910147898524',
    projectId: 'decen--backend',
    storageBucket: 'decen--backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzPrR_Rg0Dscw6HtkqIHWTzTMkwoFZCYs',
    appId: '1:910147898524:ios:e726974a43ce0b1850b159',
    messagingSenderId: '910147898524',
    projectId: 'decen--backend',
    storageBucket: 'decen--backend.firebasestorage.app',
    iosBundleId: 'com.example.whatsappUi',
  );
}
